////////////////////////////////
// htmlgumpcolor Color Values
////////////////////////////////
const HTML_BLACK := "#000000";
const HTML_DARKGRAY := "#696969"; // "#404040";
const HTML_GRAY := "#808080";
const HTML_LIGHTGRAY := "#C0C0C0";
const HTML_DARKSLATEGRAY := "#2F4F4F";
const HTML_SLATEGRAY := "#708090";
const HTML_LIGHTSLATEGRAY := "#778899";
const HTML_DARKRED := "#800000";
const HTML_RED := "#FF0000";
const HTML_DARKGREEN := "#008000";
const HTML_GREEN := "#00FF00";
const HTML_DARKYELLOW := "#808000";
const HTML_YELLOW := "#FFFF00";
const HTML_DARKORANGE := "#FF8C00";
const HTML_DARKBLUE := "#000080";
const HTML_BLUE := "#0000FF";
const HTML_DARKPURPLE := "#800080";
const HTML_PURPLE := "#FF00FF";
const HTML_DARKTURQUOISE := "#008080";
const HTML_TURQUOISE := "#00FFFF";
const HTML_WHITE := "#FFFFFF";
const HTML_SADDLEBROWN := "#8B4513";

////////////////////////////////
// xmfhtmlgumpcolor Color Values
////////////////////////////////
const XMFCOLOR_BLACK := 0;
const XMFCOLOR_WHITE := 32767;
const XMFCOLOR_BLUE1 := 15;
const XMFCOLOR_BLUE2 := 5295;
const XMFCOLOR_RED1 := 15360;
const XMFCOLOR_RED2 := 20480;
const XMFCOLOR_RED3 := 25600;
const XMFCOLOR_RED4 := 30720;
const XMFCOLOR_RED5 := 32000;
const XMFCOLOR_RED6 := 32272;
const XMFCOLOR_RED7 := 64512;
const XMFCOLOR_GRAYRED := 16715;
const XMFCOLOR_PURPLE1 := 16927;
const XMFCOLOR_PURPLE2 := 19777215;
const XMFCOLOR_GRAY1 := 15855;
const XMFCOLOR_GRAY2 := 16912;
const XMFCOLOR_OCHER1 := 23341;
const XMFCOLOR_OCHER2 := 49671;
const XMFCOLOR_OCHER3 := 90000;
const XMFCOLOR_GREEN1 := 33280;
const XMFCOLOR_GREEN2 := 33760;
const XMFCOLOR_YELLOW := 32512;
const XMFCOLOR_TURQUOISE := 1023;
const XMFCOLOR_TURQUOISEGREEN := 10000;
