name: Nightly
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "ubuntu-latest"

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Windows CL Build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: Nightly-Linux-g++
          path: Nightly-Linux-g++
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: Nightly-Linux-clang++
          path: Nightly-Linux-clang++
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: Nightly-Windows-cl
          path: Nightly-Windows-cl

      - name: Create Release zip
        run: |
          zip -j Nightly-Windows.zip Nightly-Windows-cl/*
          zip -j Nightly-Linux-gcc.zip Nightly-Linux-g++/*
          zip -j Nightly-Linux-clang.zip Nightly-Linux-clang++/*

#      - name: Create Release
#        uses: "turleypol/release_action_dist@master"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "NightlyRelease"
#          reference_release_tag: "v100.1.0"
#          prerelease: true
#          title: "Nightly Release"
#          files: |
#            Nightly-Windows.zip
#            Nightly-Linux-gcc.zip
#            Nightly-Linux-clang.zip
